version: '3.3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks:
      - kong-service
    volumes:
      - ./db:/var/lib/postgresql/data postgres
  kong:
    build: .
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PLUGINS=bundled,external-auth
      - KONG_LUA_PACKAGE_PATH=/usr/local/share/lua/5.1/kong/plugins/external-auth/?.lua;;
      - KONG_LUA_SSL_VERIFY_DEPTH=3
      - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/etc/ssl/certs/ca-certificates.pem
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    depends_on:
      - db
    networks:
      - kong-service
      - kong-gateway
  konga:
    image: pantsel/konga
    networks: 
      - kong-service
    ports:
      - 1337:1337
    depends_on:
      - kong
    environment:
      - "NODE_ENV=development"
      - "TOKEN_SECRET=secret"

networks:
  kong-service:
  kong-gateway:
    external: true